name: example
description: A new Flutter project.

version: 1.0.9+11

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter:
    path: ../
  flutter_apns: ^1.1.0
  flutter_local_notifications: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
