name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.2.0-alpha+4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.9.2
  jiffy: ^3.0.1
  cached_network_image: ^2.1.0+1
  flutter_markdown: ^0.3.4
  url_launcher: ^5.4.2
  video_player: ^0.10.8+1
  chewie: ^0.9.10
  file_picker: ^1.6.2
  image_picker: ^0.6.5
  flutter_keyboard_visibility: ^0.8.0
  stream_chat: ^0.2.0-alpha+3
  mime: ^0.9.6+3
  visibility_detector: ^0.1.4
  http_parser: ^3.1.4

dev_dependencies:
  pedantic: ^1.9.0
