name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.2.1-alpha+3

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.9.2
  rxdart: ^0.24.1
  jiffy: ^3.0.1
  flutter_portal: ^0.1.0
  cached_network_image: ^2.2.0+1
  flutter_markdown: ^0.3.5
  url_launcher: ^5.4.7
  video_player: ^0.10.11
  chewie: ^0.9.10
  file_picker: ^1.9.0+1
  image_picker: ^0.6.6+1
  flutter_keyboard_visibility: ^2.0.0
  stream_chat:
    path: ../stream_chat_dart
  mime: ^0.9.6+3
  visibility_detector: ^0.1.5
  http_parser: ^3.1.4

dev_dependencies:
  pedantic: ^1.9.0
