name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.2.11
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.1.2
  photo_view: ^0.10.1
  rxdart: ^0.24.1
  jiffy: ^3.0.1
  flutter_portal: ^0.3.0
  cached_network_image: ^2.2.0+1
  flutter_markdown: ^0.5.0
  url_launcher: ^5.4.11
  video_player: ^0.10.12+5
  chewie: ^0.9.10
  file_picker: ^2.0.8+1
  image_picker: ^0.6.7+2
  flutter_keyboard_visibility: ^3.2.1
  stream_chat: ^0.2.10+1
  flutter_emoji: ^2.2.1+1
  mime: ^0.9.6+3
  fuzzy: ^0.2.3
  visibility_detector: ^0.1.5
  http_parser: ^3.1.4
  flutter_slidable: ^0.5.4
  carousel_slider: ^2.2.1
  clipboard: ^0.1.2+8
  widgets_visibility_provider: ^2.0.2

flutter:
  assets:
    - images/giphy_icon.png
  fonts:
   - family: stream-icons
     fonts:
      - asset: fonts/stream-icons.ttf

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
