name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.2.12
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.1.2
  photo_view: ^0.10.1
  rxdart: ^0.24.1
  scrollable_positioned_list: ^0.1.8
  jiffy: ^3.0.1
  flutter_svg: ^0.19.1
  flutter_portal: ^0.3.0
  cached_network_image: ^2.2.0+1
  flutter_markdown: ^0.5.0
  url_launcher: ^5.4.11
  emojis: ^0.9.3
  video_player: ^1.0.0
  chewie: ^0.10.4
  file_picker: ^2.0.12
  image_picker: ^0.6.7+2
  flutter_keyboard_visibility: ^3.3.0
  stream_chat: ^0.2.11+1
  mime: ^0.9.6+3
  visibility_detector: ^0.1.5
  http_parser: ^3.1.4
  substring_highlight: ^0.1.2
  flutter_slidable: ^0.5.4
  carousel_slider: ^2.2.1
  clipboard: ^0.1.2+8

flutter:
  assets:
    - images/
    - svgs/
  fonts:
   - family: stream-icons
     fonts:
      - asset: fonts/stream-icons.ttf

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
