name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 0.2.23+1
repository: https://github.com/GetStream/stream-chat-dart
issue_tracker: https://github.com/GetStream/stream-chat-dart/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1
  shared_preferences: ^0.5.12+4
  logging: ^0.11.4
  dio: ^3.0.10
  web_socket_channel: ^1.1.0
  uuid: ^2.2.2
  async: ^2.4.2
  stream_channel: ^2.0.0
  moor: ^3.4.0
  path_provider: ^1.6.24
  path: ^1.7.0
  rxdart: ^0.25.0
  collection: ^1.14.13
  sqlite3_flutter_libs: ^0.3.0

dev_dependencies:
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  moor_generator: ^3.4.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  mockito: ^4.1.3
