name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 0.2.24
repository: https://github.com/GetStream/stream-chat-dart
issue_tracker: https://github.com/GetStream/stream-chat-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.7+3
  logging: ^0.11.4
  dio: ^3.0.10
  web_socket_channel: ^1.1.0
  uuid: ^2.2.2
  async: ^2.4.1
  stream_channel: ^2.0.0
  rxdart: ^0.24.1
  collection: ^1.14.12
  pedantic: ^1.9.2
  freezed: ^0.12.7
  stream_chat_persistence:
    path: ../stream_chat_persistence

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
