name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 1.5.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0
  meta: ^1.3.0
  moor: ^4.2.0
  mutex: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.4.0+1
  stream_chat:
    path: ../stream_chat

dependency_overrides:
  stream_chat:
    path: ../stream_chat

dev_dependencies:
  build_runner: ^1.11.0
  mocktail: ^0.1.0
  moor_generator: ^4.2.0
  pedantic: ^1.11.0
  test: ^1.16.0
