name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 1.0.0-beta
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  moor: ^3.4.0
  path: ^1.7.0
  path_provider: ^1.6.27
  sqlite3_flutter_libs: ^0.3.0
  stream_chat:
    path: ../stream_chat

dev_dependencies:
  test: ^1.15.7
  build_runner: ^1.11.0
  moor_generator: ^3.4.1
  pedantic: ^1.9.2
