name: stream_chat
homepage: https://getstream.io/
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 2.0.0-nullsafety.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  dio: ^4.0.0
  equatable: ^2.0.0
  freezed_annotation: ^0.14.0
  http_parser: ^4.0.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  meta: ^1.3.0
  mime: ^1.0.0
  rxdart: ^0.26.0
  uuid: ^3.0.4
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  json_serializable: ^4.1.0
  mocktail: ^0.1.1
  test: ^1.16.8
