name: stream_chat_example
description: example Flutter project using Stream Chat service

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widgets: ^0.1.11
  timeago: ^2.0.26
  jiffy: ^3.0.1
  date_format: ^1.0.8
  cached_network_image: ^2.0.0
  flutter_markdown: ^0.5.2
  url_launcher: ^5.4.2
  video_player: ^1.0.1
  chewie: 0.12.1+1
  animations: ^1.0.0+5

  stream_chat:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  build_web_compilers: any

flutter:
  uses-material-design: true
