name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 0.0.1
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  stream_chat: ^0.2.23+3
  rxdart: ^0.24.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.4
  flutter_test:
    sdk: flutter
  fake_async: ^1.1.0
  