name: stream_chat_flutter_core
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 1.5.1
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0
  stream_chat: ^1.5.0
  meta: ^1.2.4

dependency_overrides:
  stream_chat:
    path: ../stream_chat

dev_dependencies:
  fake_async: ^1.1.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

