name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 1.5.2
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter_core: ^1.5.1
  photo_view: ^0.11.0
  rxdart: ^0.26.0
  scrollable_positioned_list: ^0.1.8
  jiffy: ^3.0.1
  flutter_svg: ">=0.21.0-nullsafety.0 <0.21.0"
  flutter_portal: ^0.3.0
  cached_network_image: ">=3.0.0-nullsafety <3.0.0"
  shimmer: ^1.1.2
  flutter_markdown: ^0.5.2
  url_launcher: ^6.0.0
  emojis: ^0.9.3
  video_player: ^2.0.0
  chewie: ^1.0.0
  file_picker: ^3.0.0
  image_picker: ^0.7.0
  flutter_keyboard_visibility: ^5.0.0
  video_compress: ^2.1.1
  visibility_detector: ^0.1.5
  http_parser: ^4.0.0
  meta: ^1.3.0
  lottie: ^1.0.0
  substring_highlight: ^0.1.2
  flutter_slidable: ^0.5.7
  image_gallery_saver: ^1.6.7
  share_plus: ^2.0.0
  photo_manager: ^1.0.0
  ezanimation: ^0.4.1
  synchronized: ^3.0.0
  characters: ^1.0.0
  dio: ">=4.0.0-prev3 <4.0.0"
  path_provider: ^2.0.0
  video_thumbnail: ^0.2.5+1


dependency_overrides:
  stream_chat:
    path: ../stream_chat
  stream_chat_flutter_core:
    path: ../stream_chat_flutter_core

flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2
  golden_toolkit: ^0.6.0
  
