name: Dart Code Metrics

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  check:
    name: dart-code-metrics

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: 'packages'