name: Flutter Analyze
on:
  push:
    branches:
      - master
  
  pull_request:
    branches: 
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get

    - name: 'Flutter Format Check'
      run: flutter format --set-exit-if-changed --dry-run .

    - run: flutter analyze
